### ISSUE TITLE
Files missing under data without and missing documentation

### ISSUE THREAD

**Issue by mehrankr** [Hongyang449/Anchor#1]
Thank you for providing the code and software.
I was hoping if you could host the datasets under ```data``` in Zenodo or somewhere publicly accessible? Currently none of those files are available and it's not possible to understand the proper format of the files Anchor expects.

I also was wondering to ask if you could expand the documentation on input sequence motifs and genome sequence?
The link just says ```e.g. Hocomoco v11```, but there are many different files to download.

Thank you for your help.
I'm looking forward to use this amazing tool.

**Comment by Hongyang449** [comment]
Hi,

Thank you for your questions. 

The data used in DREAM challenge is publicly accessible. You can find the "ChIPseq", "DNASE" folders from here:
https://www.synapse.org/#!Synapse:syn6112317

For example, you can down load the DNase-seq bam files from here:
https://www.synapse.org/#!Synapse:syn6176232
The CTCF - ChIP-seq data from here:
https://www.synapse.org/#!Synapse:syn7415240

For the motif, we used the pwm file. For example, you can search "CTCF" at Hocomoco website and download the pwm from the link:
http://hocomoco11.autosome.ru/final_bundle/hocomoco11/full/HUMAN/mono/pwm/CTCF_HUMAN.H11MO.0.A.pwm

The hg19 genome can be downloaded from here:
https://www.synapse.org/#!Synapse:syn6184309

Best,
Hongyang
